// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructaDoc.Adapters.Persistence;

#nullable disable

namespace StructaDoc.Migrations.MySql.Migrations
{
    [DbContext(typeof(StructaDocDbContext))]
    [Migration("20260805080424_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StructaDoc.Adapters.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("extension");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext")
                        .HasColumnName("metadata_json");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("storage_ref");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_documents_sha256");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Adapters.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<string>("ConversionJson")
                        .HasColumnType("longtext")
                        .HasColumnName("conversion_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("external_task_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("options_json");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("char(36)")
                        .HasColumnName("provider_config_id");

                    b.Property<Guid>("ProviderConfigVersion")
                        .HasColumnType("char(36)")
                        .HasColumnName("provider_config_version");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("provider_type");

                    b.Property<string>("SourceMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_media_type");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("submitted_media_type");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_parse_runs_document_id");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_parse_runs_lease_expiry");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_parse_runs_due");

                    b.ToTable("parse_runs", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Adapters.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.HasOne("StructaDoc.Adapters.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("ParseRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("StructaDoc.Adapters.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("ParseRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
