// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructaDoc.Infrastructure.Persistence;

#nullable disable

namespace StructaDoc.Migrations.MySql.Migrations
{
    [DbContext(typeof(StructaDocDbContext))]
    [Migration("20260805145543_AddProviderSubmissionCheckpoint")]
    partial class AddProviderSubmissionCheckpoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.AdminUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("char(36)")
                        .HasColumnName("security_stamp");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_normalized_email");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ApiClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("scopes");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("api_clients", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("extension");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext")
                        .HasColumnName("metadata_json");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("storage_ref");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_documents_sha256");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_documents_created_at_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parse_run_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("storage_ref");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_parse_artifacts_sha256");

                    b.HasIndex("ParseRunId", "Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_parse_artifacts_key");

                    b.ToTable("parse_artifacts", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parse_run_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("storage_ref");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_parse_assets_sha256");

                    b.HasIndex("ParseRunId", "Name")
                        .HasDatabaseName("ix_parse_assets_name");

                    b.ToTable("parse_assets", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseBlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("asset_id");

                    b.Property<double?>("BoundingBoxX0")
                        .HasColumnType("double")
                        .HasColumnName("bbox_x0");

                    b.Property<double?>("BoundingBoxX1")
                        .HasColumnType("double")
                        .HasColumnName("bbox_x1");

                    b.Property<double?>("BoundingBoxY0")
                        .HasColumnType("double")
                        .HasColumnName("bbox_y0");

                    b.Property<double?>("BoundingBoxY1")
                        .HasColumnType("double")
                        .HasColumnName("bbox_y1");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("ContentFormat")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("content_format");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("page_number");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parse_run_id");

                    b.Property<string>("ProviderDataJson")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_data_json");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceLocatorJson")
                        .HasColumnType("longtext")
                        .HasColumnName("source_locator_json");

                    b.Property<string>("Subtype")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subtype");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ParseRunId", "AssetId")
                        .HasDatabaseName("ix_parse_blocks_asset");

                    b.HasIndex("ParseRunId", "PageNumber")
                        .HasDatabaseName("ix_parse_blocks_page");

                    b.HasIndex("ParseRunId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_parse_blocks_sequence");

                    b.ToTable("parse_blocks", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParsePageEntity", b =>
                {
                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parse_run_id");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<double?>("Height")
                        .HasColumnType("double")
                        .HasColumnName("height");

                    b.Property<string>("SourceLocatorJson")
                        .HasColumnType("longtext")
                        .HasColumnName("source_locator_json");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("unit");

                    b.Property<double?>("Width")
                        .HasColumnType("double")
                        .HasColumnName("width");

                    b.HasKey("ParseRunId", "Number");

                    b.ToTable("parse_pages", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<string>("ConversionJson")
                        .HasColumnType("longtext")
                        .HasColumnName("conversion_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("external_task_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("options_json");

                    b.Property<string>("ProtectedSubmissionContinuation")
                        .HasColumnType("longtext")
                        .HasColumnName("protected_submission_continuation");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("char(36)")
                        .HasColumnName("provider_config_id");

                    b.Property<Guid>("ProviderConfigVersion")
                        .HasColumnType("char(36)")
                        .HasColumnName("provider_config_version");

                    b.Property<string>("ProviderMetadataJson")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_metadata_json");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("provider_type");

                    b.Property<string>("ResultSchemaVersion")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("result_schema_version");

                    b.Property<string>("ResultSha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("result_sha256");

                    b.Property<string>("SourceMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_media_type");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("submitted_media_type");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_parse_runs_document_id");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_parse_runs_lease_expiry");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_parse_runs_due");

                    b.HasIndex("CreatedBy", "DocumentId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_parse_runs_idempotency");

                    b.ToTable("parse_runs", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ProviderConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("current_version_id");

                    b.Property<string>("DefaultMarker")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("default_marker");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("provider_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_provider_configs_current_version");

                    b.HasIndex("DefaultMarker")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_configs_default_marker");

                    b.ToTable("provider_configs", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ProviderConfigVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Backend")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("backend");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model");

                    b.Property<string>("ProtectedCredential")
                        .HasMaxLength(8192)
                        .HasColumnType("varchar(8192)")
                        .HasColumnName("protected_credential");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("char(36)")
                        .HasColumnName("provider_config_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConfigId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_config_versions_number");

                    b.ToTable("provider_config_versions", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseArtifactEntity", b =>
                {
                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Artifacts")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseAssetEntity", b =>
                {
                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Assets")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseBlockEntity", b =>
                {
                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Blocks")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.ParseAssetEntity", "Asset")
                        .WithMany("Blocks")
                        .HasForeignKey("ParseRunId", "AssetId")
                        .HasPrincipalKey("ParseRunId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.ParsePageEntity", null)
                        .WithMany()
                        .HasForeignKey("ParseRunId", "PageNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParsePageEntity", b =>
                {
                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Pages")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("ParseRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ProviderConfigVersionEntity", b =>
                {
                    b.HasOne("StructaDoc.Infrastructure.Persistence.Entities.ProviderConfigEntity", "ProviderConfig")
                        .WithMany("Versions")
                        .HasForeignKey("ProviderConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProviderConfig");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("ParseRuns");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseAssetEntity", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Assets");

                    b.Navigation("Blocks");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("StructaDoc.Infrastructure.Persistence.Entities.ProviderConfigEntity", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
