// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructaDoc.Platform.Persistence;

#nullable disable

namespace StructaDoc.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(StructaDocDbContext))]
    [Migration("20260805111715_AddApiClientConcurrency")]
    partial class AddApiClientConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.AdminUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_normalized_email");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ApiClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("api_clients", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_ref");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_documents_sha256");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_by");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrency_version");

                    b.Property<string>("ConversionJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversion_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_task_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("options_json");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_config_id");

                    b.Property<Guid>("ProviderConfigVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_config_version");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_type");

                    b.Property<string>("SourceMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_media_type");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_media_type");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_parse_runs_document_id");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_parse_runs_lease_expiry");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_parse_runs_due");

                    b.ToTable("parse_runs", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("ParseRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("ParseRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
