// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructaDoc.Platform.Persistence;

#nullable disable

namespace StructaDoc.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(StructaDocDbContext))]
    partial class StructaDocDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ApiClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("api_clients", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.CleanupJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StorageRefsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_refs_json");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_cleanup_jobs_due");

                    b.HasIndex("TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ux_cleanup_jobs_target");

                    b.ToTable("cleanup_jobs", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.DocumentAccessGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permissions");

                    b.Property<string>("PrincipalIssuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("principal_issuer");

                    b.Property<string>("PrincipalSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("principal_subject");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "PrincipalIssuer", "PrincipalSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_document_access_grants_principal");

                    b.ToTable("document_access_grants", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletionRequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletion_requested_at_utc");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OwnerIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_issuer");

                    b.Property<string>("OwnerSubject")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_subject");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_ref");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_documents_sha256");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_documents_created_at_id");

                    b.HasIndex("OwnerIssuer", "OwnerSubject", "CreatedAtUtc")
                        .HasDatabaseName("ix_documents_owner_created_at");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_run_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_ref");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_parse_artifacts_sha256");

                    b.HasIndex("ParseRunId", "Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_parse_artifacts_key");

                    b.ToTable("parse_artifacts", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_run_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_ref");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_parse_assets_sha256");

                    b.HasIndex("ParseRunId", "Name")
                        .HasDatabaseName("ix_parse_assets_name");

                    b.ToTable("parse_assets", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseBlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_id");

                    b.Property<double?>("BoundingBoxX0")
                        .HasColumnType("REAL")
                        .HasColumnName("bbox_x0");

                    b.Property<double?>("BoundingBoxX1")
                        .HasColumnType("REAL")
                        .HasColumnName("bbox_x1");

                    b.Property<double?>("BoundingBoxY0")
                        .HasColumnType("REAL")
                        .HasColumnName("bbox_y0");

                    b.Property<double?>("BoundingBoxY1")
                        .HasColumnType("REAL")
                        .HasColumnName("bbox_y1");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("ContentFormat")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_format");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("page_number");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_run_id");

                    b.Property<string>("ProviderDataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_data_json");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceLocatorJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_locator_json");

                    b.Property<string>("Subtype")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("subtype");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ParseRunId", "AssetId")
                        .HasDatabaseName("ix_parse_blocks_asset");

                    b.HasIndex("ParseRunId", "PageNumber")
                        .HasDatabaseName("ix_parse_blocks_page");

                    b.HasIndex("ParseRunId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_parse_blocks_sequence");

                    b.ToTable("parse_blocks", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParsePageEntity", b =>
                {
                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_run_id");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL")
                        .HasColumnName("height");

                    b.Property<string>("SourceLocatorJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_locator_json");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<double?>("Width")
                        .HasColumnType("REAL")
                        .HasColumnName("width");

                    b.HasKey("ParseRunId", "Number");

                    b.ToTable("parse_pages", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_by");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrency_version");

                    b.Property<string>("ConversionJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversion_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletionRequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletion_requested_at_utc");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_task_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle_state");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("options_json");

                    b.Property<string>("ProtectedSubmissionContinuation")
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_submission_continuation");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_config_id");

                    b.Property<Guid>("ProviderConfigVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_config_version");

                    b.Property<string>("ProviderMetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_metadata_json");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_type");

                    b.Property<string>("ResultSchemaVersion")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("result_schema_version");

                    b.Property<string>("ResultSha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("result_sha256");

                    b.Property<string>("SourceMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_media_type");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedMediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_media_type");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_parse_runs_document_id");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_parse_runs_lease_expiry");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_parse_runs_due");

                    b.HasIndex("CreatedBy", "DocumentId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_parse_runs_idempotency");

                    b.ToTable("parse_runs", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseSegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("EndPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_page");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_task_id");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("segment_index");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_run_id");

                    b.Property<string>("ProtectedSubmissionContinuation")
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_submission_continuation");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<int>("StartPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_page");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_ref");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ParseRunId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ux_parse_segments_index");

                    b.ToTable("parse_segments", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ProviderConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_version_id");

                    b.Property<string>("DefaultMarker")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_marker");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_provider_configs_current_version");

                    b.HasIndex("DefaultMarker")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_configs_default_marker");

                    b.ToTable("provider_configs", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ProviderConfigVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Backend")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("backend");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("ProtectedCredential")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_credential");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_config_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConfigId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_config_versions_number");

                    b.ToTable("provider_config_versions", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.DocumentAccessGrantEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("AccessGrants")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseArtifactEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Artifacts")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseAssetEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Assets")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseBlockEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Blocks")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ParseAssetEntity", "Asset")
                        .WithMany("Blocks")
                        .HasForeignKey("ParseRunId", "AssetId")
                        .HasPrincipalKey("ParseRunId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ParsePageEntity", null)
                        .WithMany()
                        .HasForeignKey("ParseRunId", "PageNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParsePageEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Pages")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("ParseRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseSegmentEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", "ParseRun")
                        .WithMany("Segments")
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParseRun");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ProviderConfigVersionEntity", b =>
                {
                    b.HasOne("StructaDoc.Platform.Persistence.Entities.ProviderConfigEntity", "ProviderConfig")
                        .WithMany("Versions")
                        .HasForeignKey("ProviderConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProviderConfig");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("AccessGrants");

                    b.Navigation("ParseRuns");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseAssetEntity", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ParseRunEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Assets");

                    b.Navigation("Blocks");

                    b.Navigation("Pages");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("StructaDoc.Platform.Persistence.Entities.ProviderConfigEntity", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
