// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructaDoc.Adapters.ControlPlane;

#nullable disable

namespace StructaDoc.Migrations.Sqlite.Migrations.ControlPlane
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260930101059_AddServiceMantleManagementAudit")]
    partial class AddServiceMantleManagementAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ServiceMantle.Persistence.Relational.Mapping.ManagementAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OperatorDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_display_name");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_source");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER")
                        .HasColumnName("outcome");

                    b.Property<string>("SecurityDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_description");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_occurred_at_utc_id");

                    b.HasIndex("Action", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_action_occurred_at_utc_id");

                    b.HasIndex("OperatorId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_operator_id_occurred_at_utc_id");

                    b.HasIndex("TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_id_occurred_at_utc_id");

                    b.HasIndex("TargetType", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_type_occurred_at_utc_id");

                    b.HasIndex("TargetType", "TargetId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_service_audit_logs_target_occurred_at_utc_id");

                    b.ToTable("service_audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_audit_logs_action_length", "action IS NULL OR octet_length(action) <= 800");

                            t.HasCheckConstraint("ck_service_audit_logs_client_ip_length", "client_ip IS NULL OR octet_length(client_ip) <= 256");

                            t.HasCheckConstraint("ck_service_audit_logs_correlation_id_length", "correlation_id IS NULL OR octet_length(correlation_id) <= 512");

                            t.HasCheckConstraint("ck_service_audit_logs_id_length", "id IS NULL OR octet_length(id) <= 144");

                            t.HasCheckConstraint("ck_service_audit_logs_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_service_audit_logs_metadata_json_length", "metadata_json IS NULL OR octet_length(metadata_json) <= 262144");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_display_name_length", "operator_display_name IS NULL OR octet_length(operator_display_name) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_id_length", "operator_id IS NULL OR octet_length(operator_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_operator_source_length", "operator_source IS NULL OR octet_length(operator_source) <= 400");

                            t.HasCheckConstraint("ck_service_audit_logs_security_description_length", "security_description IS NULL OR octet_length(security_description) <= 16000");

                            t.HasCheckConstraint("ck_service_audit_logs_target_id_length", "target_id IS NULL OR octet_length(target_id) <= 1024");

                            t.HasCheckConstraint("ck_service_audit_logs_target_type_length", "target_type IS NULL OR octet_length(target_type) <= 800");
                        });
                });

            modelBuilder.Entity("StructaDoc.Adapters.ControlPlane.Entities.AdminUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("LegacyNormalizedLogin")
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("legacy_normalized_login");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("LegacyNormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_legacy_normalized_login");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_normalized_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Adapters.ControlPlane.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("StructaDoc.Adapters.ControlPlane.Entities.SetupClaimEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("administrator_id");

                    b.Property<DateTime>("ClaimedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_at_utc");

                    b.Property<string>("ClaimedFromAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_from_address");

                    b.HasKey("Id");

                    b.ToTable("setup_claims", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
