<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Testcontainers.MariaDb" />
    <PackageReference Include="Testcontainers.MySql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StructaDoc.Adapters\StructaDoc.Adapters.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.MariaDb\StructaDoc.Migrations.MariaDb.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.MySql\StructaDoc.Migrations.MySql.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.PostgreSql\StructaDoc.Migrations.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.Sqlite\StructaDoc.Migrations.Sqlite.csproj" />
  </ItemGroup>

</Project>
