<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\StructaDoc.Contracts\StructaDoc.Contracts.csproj" />
    <ProjectReference Include="..\StructaDoc.Application\StructaDoc.Application.csproj" />
    <ProjectReference Include="..\StructaDoc.Infrastructure\StructaDoc.Infrastructure.csproj" />
    <ProjectReference Include="..\StructaDoc.Migrations.Sqlite\StructaDoc.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\StructaDoc.Migrations.PostgreSql\StructaDoc.Migrations.PostgreSql.csproj" />
    <ProjectReference Include="..\StructaDoc.Migrations.MySql\StructaDoc.Migrations.MySql.csproj" />
    <ProjectReference Include="..\StructaDoc.Migrations.MariaDb\StructaDoc.Migrations.MariaDb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
  </ItemGroup>

</Project>
