<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Dockerfile" Link="Dockerfile" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\scripts\build-container.ps1" Link="scripts\build-container.ps1" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\scripts\build-container.sh" Link="scripts\build-container.sh" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StructaDoc.Contracts\StructaDoc.Contracts.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Domain\StructaDoc.Domain.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Application\StructaDoc.Application.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Adapters\StructaDoc.Adapters.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.MariaDb\StructaDoc.Migrations.MariaDb.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.MySql\StructaDoc.Migrations.MySql.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.PostgreSql\StructaDoc.Migrations.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\StructaDoc.Migrations.Sqlite\StructaDoc.Migrations.Sqlite.csproj" />
  </ItemGroup>

</Project>
